A <%= @exception.class %> occurred in <%= @location %>:

  <%= @exception.message %>
  <%= @backtrace.first %>

<%- if @data[:info] -%>
<%=@data[:info].to_yaml%>
<%- end -%>

<%= @sections.map { |section| render_section(section) }.join %>
